In [1]:
import numpy as nm

In [2]:
marks = nm.array([70,75,78,85,82])
print("Student Marks are:", marks)

Student Marks are: [70 75 78 85 82]


In [4]:
roll_no = nm.arange(1,6)
print ("Roll No.:", roll_no)

Roll No.: [1 2 3 4 5]


In [7]:
per=nm.linspace(60,100,5)
print("Percentage is: ",per)

Percentage is:  [ 60.  70.  80.  90. 100.]


In [8]:
atd=nm.zeros((2,3), dtype=int)
print("Attendence: \n", atd)

Attendence: 
 [[0 0 0]
 [0 0 0]]


In [10]:
lab_status=nm.ones((2,3), dtype=int)
print("Lab Status: \n", lab_status)

Lab Status: 
 [[1 1 1]
 [1 1 1]]


In [12]:
std_id=nm.random.randint(1000,9999,5)
print("Randos Student 10s:",std_id)

Randos Student 10s: [9321 2928 8894 8123 3460]


In [14]:
arr = nm.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr.shape)

(2, 3)


In [15]:
arr = nm.ones((2, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
arr=nm.array([1,3,2,4,23,2])
print(arr.max())

23


In [17]:
arr=nm.array([1,3,2,4,23,2])
print(arr.min())

1


In [18]:
arr=nm.array([1,3,2,4,23,2])
print(arr.sum())

35


In [19]:
arr=nm.array([1,3,2,4,23,2])
print(arr.mean())

5.833333333333333


In [21]:
arr=nm.array([1,3,2,4,23,2])
print(arr.size)

6


In [22]:
arr=nm.arange(1,21)
print(arr)
print(arr[6:11])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 7  8  9 10 11]


In [23]:
#Random function
print(nm.random.rand())

0.3963870622232105


In [24]:
arr=(nm.random.randint(1,10,(2,3)))
print(arr)

[[9 4 8]
 [7 2 7]]


In [25]:
arr=(nm.random.randint(1,10,(5)))
print(arr)

[5 6 1 3 6]


In [27]:
#Boolean Indexing
mark=nm.array([23,54,68,89,87])
print(mark > 60)

[False False  True  True  True]


In [28]:
print(mark[mark>60])

[68 89 87]


In [30]:
#Cobining
arr1=nm.array([1,2,3,4])
arr2=nm.array([4,5,6,7])

print(nm.concatenate((arr1,arr2)))

[1 2 3 4 4 5 6 7]


In [32]:
#Sorting
print(nm.sort(mark))

[23 54 68 87 89]


In [33]:
print(arr1)

[1 2 3 4]


In [36]:
A = nm.array([
    [1,2],
    [3,4]
])

B = nm.array([
    [5,6],
    [7,8]
])
print(A * B)
print(nm.dot(A,B))

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
