In [1]:
import numpy as np

In [3]:
#1. Create an array
arr=np.array ([10, 20, 30, 40, 50])
print("Original Array:")
print(arr)

Original Array:
[10 20 30 40 50]


In [4]:
#2. Copy
copy_arr = arr.copy()
copy_arr[0] = 100
print("\nAfter modifying Copy:")
print("Original Array:", arr)
print("Copy Array:", copy_arr)


After modifying Copy:
Original Array: [10 20 30 40 50]
Copy Array: [100  20  30  40  50]


In [6]:
#3. View
view_arr=arr.view()
view_arr[1] = 200
print("\nAfter modifying View:")
print("Original Array:", arr)
print("View Array:", view_arr)


After modifying View:
Original Array: [ 10 200  30  40  50]
View Array: [ 10 200  30  40  50]


In [10]:
#4. Random Numbers
random_arr = np.random.randint(1, 100, 5)
print("\nRandom Array:")
print(random_arr)


Random Array:
[63 55 94 45 33]


In [13]:
#5. Searching
position= np.where (random_arr > 50)
print("\nPositions of numbers greater than 50:")
print(position)


Positions of numbers greater than 50:
(array([0, 1, 2], dtype=int64),)
